const APP_REGISTRY_DEFINITIONS = [
  {
    slug: "ai-assistant",
    name: "AI Assistant",
    description:
      "The core Pearlbot AI chatbot, knowledge base, appearance settings, Google Calendar appointments, and chat configuration.",
    category: "core",
    isCore: true,
    standalone: true,
    requiresAIAssistant: false,
    launchUrl: "/chatbot/settings",
    isVisible: true,
    isComingSoon: false,
    allowInstall: true,
    minimumPlan: "starter",
    dependencies: [],
    defaultForCustomer: true,
    sortOrder: 1,
  },
  {
    slug: "reservations",
    name: "Reservations",
    description:
      "Reservation form, reservation dashboard, booking management, capacity, opening hours, and reservation references.",
    category: "business",
    isCore: false,
    standalone: true,
    requiresAIAssistant: false,
    launchUrl: "/reservations",
    isVisible: true,
    isComingSoon: false,
    allowInstall: true,
    minimumPlan: "starter",
    dependencies: [],
    defaultForCustomer: false,
    sortOrder: 2,
  },
  {
    slug: "crm",
    name: "CRM",
    description:
      "Manage leads, customers, follow-ups, and sales opportunities.",
    category: "business",
    isCore: false,
    standalone: true,
    requiresAIAssistant: false,
    launchUrl: "/crm",
    isVisible: true,
    isComingSoon: true,
    defaultForCustomer: false,
    sortOrder: 3,
  },
  {
    slug: "analytics",
    name: "Analytics",
    description:
      "Conversation insights, booking metrics, conversion tracking, and business performance.",
    category: "analytics",
    isCore: false,
    standalone: true,
    requiresAIAssistant: false,
    launchUrl: "/analytics",
    isVisible: true,
    isComingSoon: true,
    defaultForCustomer: false,
    sortOrder: 4,
  },
  {
    slug: "facebook",
    name: "Facebook",
    description:
      "Connect a Facebook Page to the AI Assistant for Messenger conversations.",
    category: "communication",
    isCore: false,
    standalone: false,
    requiresAIAssistant: true,
    launchUrl: "/dashboard/channels/facebook",
    isVisible: true,
    isComingSoon: false,
    allowInstall: true,
    minimumPlan: "starter",
    dependencies: ["ai-assistant"],
    defaultForCustomer: true,
    icon: "Facebook",
    sortOrder: 5,
  },
  {
    slug: "whatsapp",
    name: "WhatsApp",
    description:
      "Connect Pearlbot to WhatsApp conversations and customer messaging.",
    category: "communication",
    isCore: false,
    standalone: true,
    requiresAIAssistant: true,
    launchUrl: "/whatsapp",
    isVisible: true,
    isComingSoon: true,
    defaultForCustomer: false,
    sortOrder: 5,
  },
  {
    slug: "voice-ai",
    name: "Voice AI",
    description:
      "AI voice assistant for calls, intake, routing, and customer support.",
    category: "communication",
    isCore: false,
    standalone: true,
    requiresAIAssistant: true,
    launchUrl: "/voice-ai",
    isVisible: true,
    isComingSoon: true,
    defaultForCustomer: false,
    sortOrder: 6,
  },
];

export default APP_REGISTRY_DEFINITIONS;
