import rateLimit from "express-rate-limit";
const positive = (value, fallback) => { const parsed = Number(value); return Number.isInteger(parsed) && parsed > 0 ? parsed : fallback; };
const keyGenerator = (req) => `${String(req.company?._id || "no-company")}:${String(req.userId || "no-user")}`;
const handler = (message) => (_req, res) => res.status(429).json({ success: false, code: "DIGITAL_CLONE_AVATAR_RATE_LIMITED", message });
export const DIGITAL_CLONE_AVATAR_RATE_LIMITS = Object.freeze({ discoveryPer15Minutes: positive(process.env.DIGITAL_CLONE_AVATAR_DISCOVERY_LIMIT, 10), voiceDiscoveryPer15Minutes: positive(process.env.DIGITAL_CLONE_AVATAR_VOICE_DISCOVERY_LIMIT, 10), generationPerHour: positive(process.env.DIGITAL_CLONE_AVATAR_GENERATION_LIMIT, 3), statusPer15Minutes: positive(process.env.DIGITAL_CLONE_AVATAR_STATUS_LIMIT, 120) });
export const digitalCloneAvatarDiscoveryRateLimit = rateLimit({ windowMs: 15 * 60 * 1000, limit: DIGITAL_CLONE_AVATAR_RATE_LIMITS.discoveryPer15Minutes, standardHeaders: "draft-8", legacyHeaders: false, keyGenerator, handler: handler("Too many avatar refresh requests. Please wait before trying again.") });
export const digitalCloneAvatarVoiceDiscoveryRateLimit = rateLimit({ windowMs: 15 * 60 * 1000, limit: DIGITAL_CLONE_AVATAR_RATE_LIMITS.voiceDiscoveryPer15Minutes, standardHeaders: "draft-8", legacyHeaders: false, keyGenerator, handler: handler("Too many Avatar voice refresh requests. Please wait before trying again.") });
export const digitalCloneAvatarGenerationRateLimit = rateLimit({ windowMs: 60 * 60 * 1000, limit: DIGITAL_CLONE_AVATAR_RATE_LIMITS.generationPerHour, standardHeaders: "draft-8", legacyHeaders: false, keyGenerator, handler: handler("Too many avatar video generation requests. Please wait before trying again.") });
export const digitalCloneAvatarStatusRateLimit = rateLimit({ windowMs: 15 * 60 * 1000, limit: DIGITAL_CLONE_AVATAR_RATE_LIMITS.statusPer15Minutes, standardHeaders: "draft-8", legacyHeaders: false, keyGenerator, handler: handler("Too many avatar video status requests. Please wait before trying again.") });
